config/routes.rb
PortfolioSite::Application.routes.draw do

  devise_for :users

  root to: 'projects#index'

  resources :projects, only: [:index]

  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :content, presence: true

  attr_accessible :title, :content, :posted_date, :rendered_content

  has_many :posts_tags
  has_many :tags, through: :posts_tags

  before_save :render_html

  private

    class HTMLwithPygments < Redcarpet::Render::HTML
      def block_code(code, language)
        Pygments.highlight(code, :lexer => language)
      end
    end

    def render_html
      require 'redcarpet'
      markdown = Redcarpet::Markdown.new(HTMLwithPygments, :autolink => true, :space_after_headers => true, :fenced_code_blocks => true, :strikethrough => true, :prettify => true)
      self.rendered_content = markdown.render self.content
    end

end

app/models/posts_tag.rb
class PostsTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :url, :github_url, :description

  has_many :screenshots
  has_many :skills

end

app/models/screenshot.rb
class Screenshot < ActiveRecord::Base
  attr_accessible :url

  belongs_to :project
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :name

  belongs_to :project
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence: true

  has_many :posts_tags
  has_many :posts, through: :posts_tags

  before_create { self.name.downcase! }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper TextHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.create(params[:post])
    redirect_to post_path(@post)
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])
    redirect_to post_path(@post)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/text_helper.rb
require "rubygems"
require "hpricot"

module TextHelper

  # Like the Rails _truncate_ helper but doesn't break HTML tags or entities.
  def truncate_html(text, max_length = 30, ellipsis = "...")
    return if text.nil?

    doc = Hpricot(text.to_s)
    ellipsis_length = 3
    content_length = doc.inner_text.length
    actual_length = max_length - ellipsis_length

    content_length > max_length ? doc.truncate(actual_length).inner_html + ellipsis : text.to_s
  end

end

module HpricotTruncator
  module NodeWithChildren
    def truncate(max_length)
      return self if inner_text.length <= max_length
      truncated_node = self.dup
      truncated_node.children = []
      each_child do |node|
        remaining_length = max_length - truncated_node.inner_text.length
        break if remaining_length == 0
        truncated_node.children << node.truncate(remaining_length)
      end
      truncated_node
    end
  end

  module TextNode
    def truncate(max_length)
      # We're using String#scan because Hpricot doesn't distinguish entities.
      Hpricot::Text.new(content.scan(/&#?[^\W_]+;|./).first(max_length).join)
    end
  end

  module IgnoredTag
    def truncate(max_length)
      self
    end
  end
end

Hpricot::Doc.send(:include,       HpricotTruncator::NodeWithChildren)
Hpricot::Elem.send(:include,      HpricotTruncator::NodeWithChildren)
Hpricot::Text.send(:include,      HpricotTruncator::TextNode)
Hpricot::BogusETag.send(:include, HpricotTruncator::IgnoredTag)
Hpricot::Comment.send(:include,   HpricotTruncator::IgnoredTag)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clay Whitley | Portfolio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name"><h1><a href="/">Clay Whitley</a></h1></li>
    </ul>
    <section class="top-bar-section">
      <ul class="left">
        <li><%= link_to "Work", projects_path %></li>
        <li><%= link_to "Blog", posts_path %></li>
      </ul>
    </section>
  </nav>
  <% if user_signed_in? %>
    <div class="row admin-panel">
      <div class="small-3 columns">
        Admin actions:
      </div>
      <div class="small-3 columns">
        <%= link_to "New post", new_post_path %>
      </div>
      <div class="small-3 columns">
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      </div>
    </div>
  <% end %>

  <% if notice || alert %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <% end %>

  <div class="row main-content">
    <%= yield %>
  </div>

  <!-- Footer -->
 
  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-12 columns">
          <ul class="inline-list left">
            <li><a href="https://github.com/clay-whitley/claywhitley_portfolio_site"><i class="icon-github-sign" style="font-size: 2em; color: black"></i> Source Code</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

</body>
</html>

app/views/posts/edit.html.erb
<div class="large-12 columns">
  <%= form_for @post, url: {action: "update"}, html: {class: "edit-post-form"} do |f| %>
    <%= f.text_field :title %>
    <%= f.date_select :posted_date, class: 'date-input' %>
    <%= f.text_area :content, class: 'content-input' %>

    <%= f.submit "Update" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="large-12 columns panel">
    <h3><%= post.title %></h3>
    <span>Tags:
      <% post.tags.each do |tag| %>
        <%= tag.name %>
      <% end %>
    </span>
    <br>
    <%= truncate_html(post.rendered_content, 40).gsub(/<>/, '').html_safe %>
    <%= link_to "View post", post_path(post) %>
    <% if user_signed_in? %>
      <%= link_to "Edit post", edit_post_path(post) %>
    <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="large-12 columns">
  <%= form_for @post, url: {action: "create"}, html: {class: "new-post-form"} do |f| %>
    <%= f.text_field :title, placeholder: "Title" %>
    <%= label_tag :tags, "Tags" %>
    <%= text_field_tag :tags %>
    <%= f.date_select :posted_date, class: 'date-input' %>
    <%= f.text_area :content, class: 'content-input' %>

    <%= f.submit "Create" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="large-12 columns">
  <h1><%= @post.title %></h1>
  <h3><%= @post.posted_date %></h3>
  <span>Tags:
    <% @post.tags.each do |tag| %>
        <%= tag.name %>
    <% end %>
  </span>
  <hr>
  <p>
    <%= @post.rendered_content.html_safe %>
  </p>
</div>

app/views/projects/index.html.erb
    <!-- Sidebar -->
 
    <aside class="large-3 columns right">
      <div class="row">
        <div class="large-12 small-6 columns">
          <h5>Clay Whitley</h5>
          <hr />

          <h6>Experience:</h6>
          <ul class="side-nav">
            <li><a href="#">BGC</a></li>
            <li><a href="#">DBC</a></li>
            <li><a href="#">Freelance</a></li>
          </ul>
        </div>
        <div class="large-12 small-6 columns">
          <h6>Skills:</h6>
     
          <ul class="side-nav">
            <li>HTML and HTML5</li>
            <li>CSS</li>
            <li>Javascript (including jQuery and Backbone.js)</li>
            <li>Ruby on Rails</li>
            <li>Node.js</li>
            <li>SQL and MongoDB</li>
            <li>Git and Github</li>
            <li>Photoshop and Illustrator</li>
          </ul>
        </div>
      </div>
    </aside>
 
    <!-- End Sidebar -->
 
    <!-- Main Blog Content -->
    <div class="large-9 columns" role="content">
      <div class="row">
        <div class="large-12 columns">
          <div class="row">
            <div class="small-2 columns">
              <button class="button" id="prev-project">prev</button>
            </div>
            <div class="small-8 columns">
              <table>
                <tr class="title_table_first_row">
                  <td class="title_table_left">Project:</td>
                  <td id="project_name" class=""><span id="project_id" class="right"></span></td>
                </tr>
                <tr>
                  <td class="title_table_left">Tech:</td>
                  <td id="project_tech" class="project_label">Lorem ipsum</td>
                </tr>
              </table>
            </div>  
            <div class="small-2 columns">
              <button class="button" id="next-project">next</button>
            </div>
          </div>
        </div>
      </div>
      <% @projects.each do |project| %>
        <div class="project_body" data-active="false" data-projectid="<%= project.id %>"data-projectname="<%= project.name %>" data-projecttech="<%= project.skills.map{|s|s.name}.join(', ') %>">
          <div class="row panel">
            <div class="large-12 columns">
              <% unless project.screenshots.empty? %>
                <img src=<%= project.screenshots.first.url %> alt="">
              <% end %>
            </div>
          </div>
          <div class="url-dropdown">
            URL: <%= project.url %>
          </div>
        </div>
      <% end %>
    </div>